package ch.uzh.ifi.hase.soprafs21.constant;

public enum Colours {
    BLACK, ORANGERED, CRIMSON,
    DARKORCHID, MEDIUMPURPLE, STATEBLUE,
    LIGHTSKYBLUE, DEEPSKYBLUE, SKYBLUE,
    AQUAMARINE, SEAGREEN, YELLOWGREEN,
    KHAKI, YELLOW, GOLD,
    ORANGE, DARKORANGE, BROWN,
    LIGHTGREY, DARKGREY, WHITE;
}
